### ISSUE TITLE
'Freeway_Window' object has no attribute 'freewayenv'

### ISSUE THREAD

**Issue by jeffchen006** [CenturyLiu/Carla-GUI#2]
```
Traceback (most recent call last):
  File "/home/zhiychen/Documents/Carla-GUI/gui_interface/start_sim_pop_up.py", line 75, in process_start
    self.parent_window.run()
  File "/home/zhiychen/Documents/Carla-GUI/gui_interface/freeway_window.py", line 937, in run
    self.freewayenv.max_speed = maximum_speed
AttributeError: 'Freeway_Window' object has no attribute 'freewayenv'
Aborted
```
When I run command `python3 freeway_window.py`, the above error occurs.

**Comment by grantbarry29** [comment]
It seems this error would occur if you attempt to run the simulation without having ever edited any freeway sections. Currently, the freewayenv object is only created when the user first enters the 'edit freeway' window. Because of this, if you try to run the simulation without ever editing any sections, the freewayenv object won't exist.
The fix I would suggest is the following: 
When the user runs the simulation, check if the freewayenv object has already been created. If it hasn't been created, create it and then run the simulation. If it has been created, do nothing.
Let me know if this addresses the problem.
